import os
ONEBOT_API_URL = "http://localhost:3001"
ONEBOT_API_TOKEN = os.getenv("ONEBOT_API_TOKEN")


HOST = "localhost"
PORT = 3000

BOT_QQ = 123456789
ADMIN_QQ = [123456789]

# 群聊白名单 = []
GROUP_BLACK_LIST = []

PRIVATE_BLACK_LIST = []

DATA_DIR = "./data/"


PLAYWRIGHT_CHROMIUM_ENDPOINT = ""